
parseMasterData([
        {
            "ID":0,
            "name":"Carrie",
            "scoreList":[
                ["Structure", 50],
                    ["Scope", 20],
                    ["Classes & Objects", 80],
                    ["Functions", 60],
                    ["Using Classes", 70],
                    ["Defining Classes", 80],
                    ["Defining Functions", 30],
                    ["Returning Values", 10],
                    ["Parameters", 95],
                    ["Calling Functions", 45],
                    ["Arguments", 85],
                    ["Catching Return Values", 65],

                    ["Data", 24],
                    ["Assignment", 80],
                    ["Literals", 65],
                    ["Variables", 82],
                    ["Expressions", 40],
                    ["Math Expressions", 30],
                    ["Boolean Expressions", 73],
                    ["Int", 82],
                    ["Float", 55],
                    ["Boolean", 95],
                    ["Data Types", 76],

                    ["Control", 58],
                    ["If Statement", 88],
                    ["Loop", 90],
                    ["While Loop", 40],
                    ["For Loop", 55],
                    ["Collections", 78],
                    ["String", 55],
                    ["List", 40]
            ]
        },
        
        {
            "ID":1,
            "name":"Bob",
            "scoreList":[
                ["Structure", 45],
                    ["Scope", 78],
                    ["Classes & Objects", 65],
                    ["Functions", 12],
                    ["Using Classes", 54],
                    ["Defining Classes", 85],
                    ["Defining Functions", 25],
                    ["Returning Values", 45],
                    ["Parameters", 78],
                    ["Calling Functions", 65],
                    ["Arguments", 88],
                    ["Catching Return Values", 43],

                    ["Data", 44],
                    ["Assignment", 55],
                    ["Literals", 56],
                    ["Variables", 40],
                    ["Expressions", 67],
                    ["Math Expressions", 85],
                    ["Boolean Expressions", 35],
                    ["Int", 45],
                    ["Float", 68],
                    ["Boolean", 95],
                    ["Data Types", 52],

                    ["Control", 95],
                    ["If Statement", 96],
                    ["Loop", 80],
                    ["While Loop", 45],
                    ["For Loop", 85],
                    ["Collections", 35],
                    ["String", 88],
                    ["List", 99]
            
            ]
        },
        
        {
            "ID":2,
            "name":"Alice",
            "scoreList":[
                ["Structure", 75],
                    ["Scope", 88],
                    ["Classes & Objects", 50],
                    ["Functions", 64],
                    ["Using Classes", 88],
                    ["Defining Classes", 55],
                    ["Defining Functions", 45],
                    ["Returning Values", 35],
                    ["Parameters", 80],
                    ["Calling Functions", 65],
                    ["Arguments", 76],
                    ["Catching Return Values", 34],

                    ["Data", 85],
                    ["Assignment", 55],
                    ["Literals", 76],
                    ["Variables", 89],
                    ["Expressions", 99],
                    ["Math Expressions", 46],
                    ["Boolean Expressions", 76],
                    ["Int", 81],
                    ["Float", 50],
                    ["Boolean", 64],
                    ["Data Types", 86],

                    ["Control", 35],
                    ["If Statement", 43],
                    ["Loop", 56],
                    ["While Loop", 43],
                    ["For Loop", 44],
                    ["Collections", 88],
                    ["String", 50],
                    ["List", 89]
            ]
        },
    {
            "ID":3,
            "name":"Dave",
            "scoreList":[
                ["Structure", 65],
                    ["Scope", 55],
                    ["Classes & Objects", 78],
                    ["Functions", 90],
                    ["Using Classes", 50],
                    ["Defining Classes", 10],
                    ["Defining Functions", 87],
                    ["Returning Values", 63],
                    ["Parameters", 90],
                    ["Calling Functions", 40],
                    ["Arguments", 25],
                    ["Catching Return Values", 80],

                    ["Data", 94],
                    ["Assignment", 54],
                    ["Literals", 25],
                    ["Variables", 10],
                    ["Expressions", 60],
                    ["Math Expressions", 50],
                    ["Boolean Expressions", 40],
                    ["Int", 48],
                    ["Float", 52],
                    ["Boolean", 25],
                    ["Data Types", 96],

                    ["Control", 80],
                    ["If Statement", 45],
                    ["Loop", 20],
                    ["While Loop", 52],
                    ["For Loop", 58],
                    ["Collections", 65],
                    ["String", 46],
                    ["List", 33]
            ]
        }
    ]);